frps 控制面板
从 https://github.com/superzjg/luci-app-frpc_frps 拷贝

diff --git a/root/etc/init.d/frps b/root/etc/init.d/frps
--- a/root/etc/init.d/frps
+++ b/root/etc/init.d/frps
@@ -26,19 +26,77 @@ _err() {
 	_log "err" $@
 }
 
+# 因Uci的option名不能带 . 号，故用 __ 替代；在调用此函数时，frp参数名称，分3类
+# 1.Toml字符串类，直接使用，并加双引号输出
+# 2.Toml布尔和整数，使用时，名称请附加 ..INT 后缀，在此处理后，并原样输出
+# 3.Toml数组，使用时请附加 ..ARR 后缀，网页端可 不加引号使用逗号或空格分隔 的简写方式，处理后，再加方括号输出
+# 4.uci值存在单独的 * 号时（如frpc参数allowUsers），可能导致for取值异常，要处理
 append_options() {
 	local file="$1" ; shift
-	local o v
+	local o v f
 	for o in "$@" ; do
-		v="$(eval echo "\$$o")"
+		f=""
+		if [ -n "$(echo $o | grep "..INT")" ];then
+            f=1
+            o=${o//..INT/}
+		fi
+        if [ -n "$(echo $o | grep "..ARR")" ];then
+            f=2
+            o=${o//..ARR/}
+        fi
+		eval v=\$${o//./__}
 		if [ -n "$v" ] ; then
-			# add brackets when ipv6 address
-			if ( echo "$o" | grep -qE 'addr|ip' ) &&
-				( echo "$v" | grep -q ':' ) ; then
-				v="[$v]"
-			fi
-
-			echo "${o} = $v" >>"$file"
+			[ "$f" == "" ] && echo "$o = \"$v\"" >>"$file"
+			[ "$f" == "1" ] && echo "$o = $v" >>"$file"
+            if [ "$f" == "2" ];then
+                local T M
+                M=""
+                if [ "$o" == "allowPorts" ];then
+                    # 对allowPorts特殊处理，标准写法和简写法
+                    if [ -n "$(echo "$v" | grep "{" | grep "}")" ];then
+                        echo "$o = [ $v ]" >>"$file"
+                    else
+                        v=${v//,/ }
+                        for T in $v ; do
+                        if [ -z "$(echo "$T" | grep "\-")" ];then
+                            T="{ single = $T }"
+                        else
+                            [ "${T%-*}" -ge "${T#*-}" ] && continue
+                            T="{ start = ${T%-*}, end = ${T#*-} }"
+                        fi
+                        [ -n "$M" ] && M="$M, "
+                        M=$M$T
+                        done
+                        echo "$o = [ $M ]" >>"$file"
+                    fi
+                else
+                    # 逗号替换为空格
+                    v=${v//,/ }
+                    # 查找单个的 * ，替换为 "*" 。
+                    if [ -n "$(echo "$v" | grep "^\* \| \* \| \*$")" ];then
+                        v="${v//\*/\"*\"}"
+                    fi
+                    [ "$v" == "*" ] && v=\"*\"
+                    for T in $v ; do    
+                    # 忽略单个的 ' 或 " 符。
+                    if [ "${T:0:1}" == "\"" -o "${T:0:1}" == "'" ] && [ "${#T}" == "1" ];then
+                        continue
+                    fi
+                    # 除首尾同是 ' 或同是 " 外，删除所有 ' 或 " ，并补全首尾的 " 。
+ #                   if [ "${T:0:1}" == "\"" -a "${T: -1}" == "\"" ] || [ "${T:0:1}" == "'" -a "${T: -1}" == "'" ];then
+					if [ "${T:0:1}" == "\"" -a "$(echo -n "$T" | tail -c 1)" == "\"" ] || [ "${T:0:1}" == "'" -a "$(echo -n "$T" | tail -c 1)" == "'" ];then
+                        true
+                    else
+                        T=${T//\'/}
+                        T=\"${T//\"/}\"
+                    fi
+                    # 用逗号+空格组合
+                    [ -n "$M" ] && M="$M, "
+                    M=$M$T
+                    done
+                    echo "$o = [$M]" >>"$file"
+                fi
+            fi
 		fi
 	done
 }
@@ -56,26 +114,42 @@ frps_scetion_validate() {
 		'enabled:bool:0' \
 		'client_file:file:/usr/bin/frps' \
 		'run_user:string' \
+		'set_firewall:string' \
+		'tcp_ports:string' \
+		'udp_ports:string' \
 		'enable_logging:bool:0' \
-		'log_file:string:/var/log/frps.log' \
-		'log_level:or("trace", "debug", "info", "warn", "error"):warn' \
-		'log_max_days:uinteger:3' \
-		'disable_log_color:or("true", "false")' \
-		'max_pool_count:uinteger' \
-		'max_ports_per_client:uinteger:0' \
-		'subdomain_host:host' \
-		'dashboard_addr:host' \
-		'dashboard_port:port' \
-		'dashboard_user:string' \
-		'dashboard_pwd:string' \
-	    'bind_port:port' \
-		'token:string' \
-		'tcp_mux:or("true", "false"):true' \
-		'tls_only:or("true", "false"):false' \
-		'bind_udp_port:port' \
-		'kcp_bind_port:port' \
-		'vhost_http_port:port' \
-		'vhost_https_port:port'
+		'std_redirect:bool:0' \
+		'log__to:string' \
+		'log__level:or("trace", "debug", "info", "warn", "error")' \
+		'log__maxDays:uinteger' \
+		'log__disablePrintColor:or("true", "false")' \
+		'bindAddr:string' \
+		'bindPort:integer' \
+		'auth__method:or("token", "oidc")' \
+		'auth__token:string' \
+		'transport__tcpMux:or("true", "false")' \
+		'transport__tcpMuxKeepaliveInterval:uinteger' \
+		'kcpBindPort:port' \
+		'quicBindPort:port' \
+		'vhostHTTPPort:port' \
+		'vhostHTTPSPort:port' \
+		'transport__maxPoolCount:uinteger' \
+		'maxPortsPerClient:uinteger' \
+		'allowPorts:string' \
+		'subDomainHost:host' \
+		'transport__tls__force:or("true", "false")' \
+		'transport__tls__certFile:file' \
+		'transport__tls__keyFile:file' \
+		'transport__tls__trustedCaFile:file' \
+		'transport__heartbeatTimeout:integer' \
+		'proxyBindAddr:string' \
+		'extra_setting:list(string)' \
+		'webServer__addr:host' \
+		'webServer__port:port' \
+		'webServer__user:string' \
+		'webServer__password:string' \
+		'webServer__tls__certFile:file' \
+		'webServer__tls__keyFile:file'
 }
 
 client_file_validate() {
@@ -96,53 +170,115 @@ create_config_file() {
 	local config_file="$1"
 	local tmp_file="$(mktemp /tmp/frps-XXXXXX)"
 
-	echo "[common]" > "$tmp_file"
+	echo "# 文件生成时间：$(date +%Y-%m-%d_%H:%M:%S)" > "$tmp_file"
 	
 	append_options "$tmp_file" \
-		"bind_port" "token" "tcp_mux" "tls_only" "bind_udp_port" "kcp_bind_port" "vhost_http_port" "vhost_https_port" 
-
+		"bindAddr" "bindPort..INT" "proxyBindAddr" "auth.method" "auth.token" "kcpBindPort..INT" "quicBindPort..INT" \
+		"vhostHTTPPort..INT" "vhostHTTPSPort..INT" "transport.tcpMux..INT" "transport.tcpMuxKeepaliveInterval..INT"
 
 	if [ "x$enable_logging" = "x1" ] ; then
-		if [ -z "$log_file" ]; then
-			log_file="/var/log/frps.log"
-		fi
-
+	
 		append_options "$tmp_file" \
-			"log_file" "log_level" "log_max_days" "disable_log_color"
-
-		if [ -f "$log_file" ] ; then
-			echo > "$log_file"
-		else
-			local log_folder="$(dirname "$log_file")"
-
-			if [ ! -d "$log_folder" ] ; then
-				mkdir -p "$log_folder"
-			fi
-		fi
-
-		if [ -n "$run_user" ] && ( user_exists "$run_user" ) ; then
-			chmod 644 "$log_file"
-			chown "$run_user" "$log_file"
-		else
-			run_user=""
-		fi
+			"log.to" "log.level" "log.maxDays..INT" "log.disablePrintColor..INT"
 	fi
 
 	append_options "$tmp_file" \
-		"max_pool_count" "max_ports_per_client" "subdomain_host" "dashboard_addr" "dashboard_port" "dashboard_user" "dashboard_pwd"
+		"transport.maxPoolCount..INT" "maxPortsPerClient..INT" "transport.heartbeatTimeout..INT" "subDomainHost" "allowPorts..ARR" \
+		"transport.tls.force..INT" "transport.tls.certFile" "transport.tls.keyFile" "transport.tls.trustedCaFile" \
+		"webServer.addr" "webServer.port..INT" "webServer.user" "webServer.password" "webServer.tls.certFile" "webServer.tls.keyFile"
 
-	extra_setting=$(uci get frps.main.extra_setting 2>/dev/null)
-	if [ -n "$extra_setting" ] ; then
-		for o in $extra_setting ;do
-			echo "$o" >> "$tmp_file"
-		done
-	fi
-
+    config_list_foreach "$section" "extra_setting" add_rule_extra_option "$tmp_file"
+    
 	sed '/^$/d' "$tmp_file" >"$config_file"
 
 	if [ "$?" = "0" ] ; then
 		rm -f "$tmp_file"
 	fi
+}
+
+add_firewall() {
+    if [ "$set_firewall" != "no" ]; then
+    local mark1=0
+    local mark2=0
+        if [ -n "$tcp_ports" ]; then
+            mark1=1
+            [ "$set_firewall" == "check" ] && [ "$tcp_ports" == "$(uci -q get firewall.frps_t_auto.dest_port)" ] && mark1=0
+            if [ "$mark1" == "1" ]; then
+                uci -q delete firewall.frps_t_auto
+                uci set firewall.frps_t_auto=rule
+                uci set firewall.frps_t_auto.name="frps_t_auto"
+                uci set firewall.frps_t_auto.target="ACCEPT"
+                uci set firewall.frps_t_auto.src="wan"
+                uci set firewall.frps_t_auto.proto="tcp"
+                uci set firewall.frps_t_auto.dest_port="$tcp_ports"
+                uci set firewall.frps_t_auto.enabled="1"
+            fi    
+        fi	    
+		if [ -n "$udp_ports" ]; then
+		    mark2=1
+            [ "$set_firewall" == "check" ] && [ "$udp_ports" == "$(uci -q get firewall.frps_u_auto.dest_port)" ] && mark2=0
+            if [ "$mark2" == "1" ]; then
+                uci -q delete firewall.frps_u_auto
+                uci set firewall.frps_u_auto=rule
+                uci set firewall.frps_u_auto.name="frps_u_auto"
+                uci set firewall.frps_u_auto.target="ACCEPT"
+                uci set firewall.frps_u_auto.src="wan"
+                uci set firewall.frps_u_auto.proto="udp"
+                uci set firewall.frps_u_auto.dest_port="$udp_ports"
+                uci set firewall.frps_u_auto.enabled="1"
+            fi    
+        fi
+        [ "$mark1" == "0" ] && [ "$mark2" == "0" ] && return 0
+		uci commit firewall
+		/etc/init.d/firewall reload >/dev/null 2>&1
+	fi
+}
+
+del_firewall() {
+    if [ "$set_firewall" == "force" ]; then
+        local A=$(uci -q show firewall.frps_t_auto)
+        local B=$(uci -q show firewall.frps_u_auto)
+        [ -n "$A" ] && uci -q delete firewall.frps_t_auto
+        [ -n "$B" ] && uci -q delete firewall.frps_u_auto
+        if [ -n "$A" ] || [ -n "$B" ]; then
+            uci commit firewall
+            /etc/init.d/firewall reload >/dev/null 2>&1
+        fi    
+    fi
+}
+logfile_prepare() {
+    if [ "x$enable_logging" != "x1" ];then
+        rm -f /tmp/frps_log_link.txt
+        rm -f /tmp/frps_std_redirect.log
+        echo "未配置日志输出保存" > /tmp/frps_log_link.txt
+        return 1
+    fi
+    
+    if [ "${std_redirect}" == "1" ];then
+        if [ -z "${log__to}" -o "${log__to}" == "console" ];then
+            log__to=/tmp/frps_std_redirect.log
+            true >"${log__to}"
+        else
+            mkdir -p "$(dirname "${log__to}")"
+            touch "${log__to}"
+            if [ "$?" != "0" ];then
+                log__to=/tmp/frps_std_redirect.log
+                echo "【$(date +%Y-%m-%d_%H:%M:%S)】--->警告：配置的日志文件路径似乎无效/只读！" > "${log__to}"
+            fi
+        fi
+    fi
+    
+    if [ -n "${log__to}" -a "${log__to}" != "console" ];then
+        mkdir -p "$(dirname "${log__to}")"
+        touch "${log__to}"
+    fi
+    
+    if [ -n "$run_user" ]; then
+        chmod 644 "$log__to"
+        chown "$run_user" "$log__to"
+    fi
+    # 创建log文件读取链接，用于luci查看日志
+    ln -sf "${log__to}" /tmp/frps_log_link.txt
 }
 
 start_instance() {
@@ -155,6 +291,7 @@ start_instance() {
 
 	if [ "x$enabled" != "x1" ] ; then
 		_info "Instance \"$section\" disabled."
+		del_firewall
 		return 1
 	fi
 
@@ -165,7 +302,7 @@ start_instance() {
 
 	test -d "$CONFIG_FOLDER" || mkdir -p "$CONFIG_FOLDER"
 
-	local config_file="$CONFIG_FOLDER/frps.$section.ini"
+	local config_file="$CONFIG_FOLDER/frps.$section.toml"
 
 	create_config_file "$config_file"
 
@@ -173,18 +310,25 @@ start_instance() {
 		_err "Could not create config file: \"$config_file\""
 		return 1
 	fi
+	
+	logfile_prepare
 
 	procd_open_instance "$NAME.$section"
-	procd_set_param command "$client_file"
-	procd_append_param command -c "$config_file"
+	if [ "${std_redirect}" == "1" ];then
+	    procd_set_param command "/bin/sh"
+	    procd_append_param command -c "exec $client_file -c $config_file >>\"${log__to}\" 2>&1"
+	else
+    	procd_set_param command "$client_file"
+    	procd_append_param command -c "$config_file"
+	fi
 	procd_set_param respawn
 	procd_set_param file "$config_file"
-
 	if [ -n "$run_user" ] ; then
 		procd_set_param user "$run_user"
 	fi
-
 	procd_close_instance
+	
+	add_firewall
 }
 
 service_triggers() {
@@ -194,4 +338,10 @@ service_triggers() {
 start_service() {
 	config_load "$NAME"
 	config_foreach start_instance "frps"
+}
+stop_service() {
+#	config_load "$NAME"
+#	config_get set_firewall main set_firewall
+    set_firewall=$(uci get frps.main.set_firewall 2>/dev/null)
+	del_firewall
 }
